graphmake: main.cpp basic_graph.cpp module_1.cpp module_2.cpp module_3.cpp module_4.cpp module_5.cpp
	g++ -o graphmake main.cpp basic_graph.cpp module_1.cpp module_2.cpp module_3.cpp module_4.cpp module_5.cpp
